steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/general-495307/swipesync-frontend', '-f', 'frontend/Dockerfile.frontend', '.']
images: ['gcr.io/general-495307/swipesync-frontend']
