steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/general-495307/swipesync-backend', '-f', 'server/Dockerfile.backend', '.']
images: ['gcr.io/general-495307/swipesync-backend']
